### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by knghtbrd** [libretro/libretro-3dengine#2]
This module doesn't appear to specify a license or anything.  That should be corrected at some point.

**Comment by ghost** [comment]
Dunno if you were ever made aware of this in the time since opening this issur but the source files currently state a GPLv3 or later license

/*
-  Libretro 3DEngine
-  Copyright (C) 2013-2014 - Hans-Kristian Arntzen
-  Copyright (C) 2013-2014 - Daniel De Matteis
  *
-  Libretro 3DEngine is free software: you can redistribute it and/or modify it under the terms
-  of the GNU General Public License as published by the Free Software Found-
-  ation, either version 3 of the License, or (at your option) any later version.
  *
-  Libretro 3DEngine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
-  PURPOSE.  See the GNU General Public License for more details.
  *
-  You should have received a copy of the GNU General Public License along with Libretro 3DEngine.
-  If not, see http://www.gnu.org/licenses/.
  */
